name: text_form_field_wrapper
description: A ui wrapper for expressing border shapes around text form fields
version: 1.0.0
homepage: https://github.com/jonesw5/text_form_field_wrapper

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:


